name: Build and Deploy to Netlify
on:
  push:
  pull_request:

permissions:
  # for create-a-commit-status
  statuses: write
  # for create-a-deployment
  deployments: write

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Netlify
        uses: nojvek/actions-netlify@adac04d0ed06a083230641bb15d8ccdc971a733a
        with:
          publish-dir: './public'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
